export { default as Navbar } from "./navbar/Navbar.tsx";
export { default as Hero } from "./hero/Hero.tsx";
export { default as Skills } from "./skills/Skills.tsx";
export { default as Projects } from "./projects/Projects.tsx";
export { default as Contact } from "./contact/Contact.jsx";
export { default as Resume } from "./resume/Resume.tsx";
export { default as AboutSkill } from "./aboutskill/Aboutskill.tsx";
export { default as Experience } from "./experience/Experience.jsx";
export { default as ErrorPage } from "./errorPage/ErrorPage.jsx";